In [17]:
import pandas as pd
import numpy as np
from IPython.display import display, HTML

# Load the CSV file into a DataFrame
file_path_1 = '50p_2000r_20x.csv'
df1 = pd.read_csv(file_path_1)
# Extract statistics of each column
statistics1 = df1.describe()

# Load the CSV file into a DataFrame
file_path_2 = '5000p_2000r_20x.csv'
df2 = pd.read_csv(file_path_2)
# Extract statistics of each column
statistics2 = df2.describe()

# Display both tables side by side with titles
display(HTML(f"""
<table>
    <tr>
        <th>Statistics for 50p_2000r_20x.csv</th>
        <th>Statistics for 5000p_2000r_20x.csv</th>
    </tr>
    <tr>
        <td>{statistics1.to_html()}</td>
        <td>{statistics2.to_html()}</td>
    </tr>
</table>
"""))

In [ ]:
import pandas as pd
import numpy as np
from IPython.display import display, HTML

# Load the CSV file into a DataFrame
file_path_1 = '50p_2000r_20x.csv'
df1 = pd.read_csv(file_path_1)
# Extract statistics of each column
statistics1 = df1.describe()

# Load the CSV file into a DataFrame
file_path_2 = '5000p_2000r_20x.csv'
df2 = pd.read_csv(file_path_2)
# Extract statistics of each column
statistics2 = df2.describe()

# Display both tables side by side with titles
display(HTML(f"""
<table>
    <tr>
        <th>Statistics for 50p_2000r_20x.csv</th>
        <th>Statistics for 5000p_2000r_20x.csv</th>
    </tr>
    <tr>
        <td>{statistics1.to_html()}</td>
        <td>{statistics2.to_html()}</td>
    </tr>
</table>
"""))

In [13]:
statistics1

,Tempo de resposta,Latencia,"Error (0 = OK, 1 = Error)",CPU (%),Memoria (MB)
count,39994.000000,39994.000000,39994.000000,39993.000000,39993.000000
mean,32.091377,32.070947,0.027279,23.583107,4478.403059
std,18.520302,18.520276,0.162898,10.034205,108.744556
min,0.198996,0.180724,0.000000,0.000000,4181.847656
25%,16.181655,16.159236,0.000000,17.100000,4412.484375
50%,31.885592,31.867317,0.000000,22.600000,4466.285156
75%,47.600996,47.580440,0.000000,28.600000,4518.324219
max,74.805025,74.790690,1.000000,100.000000,5348.789062

In [14]:
statistics2

,Tempo de resposta,Latencia,"Error (0 = OK, 1 = Error)",CPU (%),Memoria (MB)
count,39993.000000,39993.000000,39993.000000,39991.000000,39991.000000
mean,67.789316,67.765613,0.104818,17.238196,3652.781942
std,44.656159,44.656188,0.306323,8.835990,93.680846
min,0.220421,0.194035,0.000000,0.000000,3228.957031
25%,31.133443,31.105341,0.000000,11.100000,3595.341797
50%,62.090843,62.068323,0.000000,15.300000,3644.382812
75%,98.442922,98.421794,0.000000,20.700000,3719.021484
max,200.963520,200.935651,1.000000,76.100000,3981.523438