In [3]:
import pandas as pd
import numpy as np
from IPython.display import display, HTML

# Load the CSV file into a DataFrame
file_path_1 = '50p_500r_20x.csv'
df1 = pd.read_csv(file_path_1)
# Extract statistics of each column
statistics1 = df1.describe()

# Load the CSV file into a DataFrame
file_path_2 = '50000p_500r_2x.csv'
df2 = pd.read_csv(file_path_2)
# Extract statistics of each column
statistics2 = df2.describe()

# Create HTML for each column's statistics side by side
html_content = "<div style='display: flex; flex-wrap: wrap;'>"

for column in statistics1.columns:
    html_content += f"""
    <div style='margin: 10px;'>
        <h3>{file_path_1}</h3>
        {statistics1[column].to_frame().to_html()}
    </div>
    <div style='margin: 10px;'>
        <h3>{file_path_2}</h3>
        {statistics2[column].to_frame().to_html()}
    </div>
    <div style='border-left: 1px solid white; padding-left: 10px;'></div>
    """

html_content += "</div>"

# Display the final HTML
display(HTML(html_content))